unique_ids:
  assets:
    standard-page.html: AYQ5GCH5CYCTDYDKBI7TCAX6IFYDPA7X
    theme.css: HEL3CTUKSOZ2PYO7FV4C2SZZXB26XSHG
  forms:
    Form1: NZBA3AYTHCO2H3VSUHKCDCDL7J3MSXAV
  modules: {}
  scripts: {}
  server_modules: {}
